/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoFinal;

/**
 *
 * @author vinic
 */

public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextPane();
        seletor_decada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel1.setText("Ciências Humanas");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Coloque uma década/ano:");

        Buscar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Fechar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                resultadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(resultado);

        seletor_decada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seletor_decada, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_decada))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FecharActionPerformed

    private void resultadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_resultadoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoAncestorAdded

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        int decada_selecionada = Integer.valueOf(seletor_decada.getText());
        String [] acontecimentos = {"10'\n - 1912 14 - 15 de abril - Naufrágio do transatlântico RMS Titanic após o choque contra"
            + " um iceberg no Atlântico Norte, causando a morte de mais de 1500 pessoas. \n - 1914 28 de julho - Império "
            + "Austro-Húngaro declara guerra ao Reino da Sérvia; Início da Primeira Guerra Mundial."
            + "\n - 1918 11 de novembro — A assinatura do Armistício de Compiègne encerra os combates da Primeira Guerra"
            + " Mundial, com as Potências Aliadas derrotando os Impérios Centrais.",
        "20'\n - 1922 11 de Fevereiro - Inicia a Semana de Arte Moderna em São Paulo.\n - 1926 1 de março: É"
            + " realizada a eleição presidencial direta. Washington Luís é eleito presidente da República"
            + " com 688.528 votos.\n - 1929 29 de Outubro - Terça-Feira Negra marca o início da Grande Depressão.",
        "30'\n - 1930 3 de Outubro - Revolução de 1930: Em Porto Alegre, tomada do quartel-general da 3ª Região Militar,"
            + " inicia a chamada revolução.\n - 1933 30 de Janeiro- Adolf Hitler foi nomeado chanceler da Alemanha"
            + " ( Reichskanzler) por Hindenburg (a Machtergreifung), sendo o gabinete ministerial em seguida dissolvido"
            + " por Hitler.\n - 1937 30 de Setembro - Plano Cohen: O Plano é divulgado nas rádios e o Brasil entra em "
            + "Estado de Guerra.\n - 1939 1 de setembro - Início da Segunda Guerra Mundial (Invasão da Polônia).", 
        "40'\n - 1945 2 de setembro — Termina a Segunda Guerra Mundial, Com a vitória Aliada.\n - 1948 14 de maio"
            + " — O Estado de Israel se torna independente.\n - 1949 4 de abril — Criação da Organização do"
            + " Tratado do Atlântico Norte (OTAN ou NATO).", 
        "50'\n - 1951 6 de Dezembro - Vargas apresenta o projeto de criação da Petrobrás.\n - 1955 14 de maio"
            + " - O Pacto de Varsóvia é criado para combater a OTAN.\n 1958 29 de julho — Foi fundada"
            + " a NASA em Washington, D.C.", 
        "60'\n - 1962 9 de janeiro — Cuba e a União Soviética assinaram um pacto de comércio.\n - 1964 1 de abril"
            + " - João Goulart, presidente do Brasil é derrubado pelos militares, sendo sucedido pelo presidente"
            + " da Câmara dos Deputados, Ranieri Mazzilli\n - 1968 13 de Dezembro - AI-5 é editado pelo Congresso"
            + " e sancionado pelo presidente Costa e Silva, fechando o Congresso Nacional gerando caos no país.\n "
            + "- 1976 24 de março - A Presidente da Argentina Isabelita Perón é deposta por um Golpe de Estado e começa"
            + " um período de Ditadura na Argentina.\n - 1 de abril - Steve Jobs e Steve Wozniac lançam a Apple Inc.\n "
            + "- 1977 25 de maio - Star Wars, filme dirigido pelo estadunidense George Lucas, é lançado nos cinemas, se"
            + " tornando o filme de maior bilheteria de todos os tempos.", 
        "70'\n - 1971 5 de Fevereiro - O módulo Antares (Apollo 14) do Programa Apollo, desenvolvido pela NASA, pousou"
            + " na cratera Fra Mauro da superfície lunar.\n - 1972 1 de julho - Acontece a primeira marcha do orgulho LGBT"
            + " na Inglaterra\n - 1974 15 de março - O General Ernesto Geisel substitui o General Emílio Garrastazu Médici"
            + " no cargo de presidente do Brasil.", 
        "80'\n - 1985 15 de março - fim da ditadura militar no Brasil\n - 1986 1 de janeiro - Adesão de Portugal à União Europeia\n "
            + "- 1988 5 de outubro - Promulgação da Constituição Brasileira de 1988.",
        "90'\n - 1990 17 de maio - A homossexualidade foi retirada da Classificação Internacional de Doenças pela Organização"
            + " Mundial da Saúde (OMS).\n - 1991 26 de março - Brasil, Argentina, Uruguai e Paraguai assinam o Tratado"
            + " de Assunção, que estabelece o Mercosul.\n - 1992 29 de setembro – No Brasil, a Câmara dos Deputados aprova"
            + " o pedido de Impeachment e Fernando Collor de Mello é afastado do governo. O seu vice, Itamar Franco, assume"
            + " o cargo de Presidente.\n - 1993 26 de fevereiro - Ataque a bomba ao World Trade Center.",
        "2000'\n - 2000 26 de março - Vladimir Putin é eleito presidente da Rússia.\n - 2001 11 de Setembro"
            + " - As torres do World Trade Center, em Nova York, são destruídas e o Pentágono, em Washington"
            + " D.C, sofre grandes perdas após um ataque terrorista atribuído ao saudita Osama Bin Laden."
            + " Pelo incidente foi considerado o maior ataque terrorista da História. O temor de um conflito"
            + " mundial em que a economia se desequilibrou em todo o mundo\n - 2005 14 de Fevereiro - "
            + "Fundação do Youtube, e seu primeiro vídeo",
        "2010'\n - 2010 Dilma Rousseff é eleita a primeira mulher presidente do Brasil.\n - 2011 A Guerra do Iraque"
            + " chega ao fim, após 8 anos de existência\n - 2019 Incêndio atinge a catedral mais visitada do mundo,"
            + " a Catedral de Notre-Dame em Paris."};
        if (decada_selecionada >= 1910 && decada_selecionada <=1919 || decada_selecionada == 10){
            resultado.setText(acontecimentos[0]);
        } else if (decada_selecionada >= 1920 && decada_selecionada <=1929 || decada_selecionada == 20){
            resultado.setText(acontecimentos[1]);
        } else if (decada_selecionada >= 1930 && decada_selecionada <=1939 || decada_selecionada == 30){
            resultado.setText(acontecimentos[2]);
        } else if (decada_selecionada >= 1940 && decada_selecionada <=1949 || decada_selecionada == 40){
            resultado.setText(acontecimentos[3]);
        } else if (decada_selecionada >= 1950 && decada_selecionada <=1959 || decada_selecionada == 50){
            resultado.setText(acontecimentos[4]);
        } else if (decada_selecionada >= 1960 && decada_selecionada <=1969 || decada_selecionada == 60){
            resultado.setText(acontecimentos[5]);
        } else if (decada_selecionada >= 1970 && decada_selecionada <=1979 || decada_selecionada == 70){
            resultado.setText(acontecimentos[6]);
        } else if (decada_selecionada >= 1980 && decada_selecionada <=1989 || decada_selecionada == 80){
            resultado.setText(acontecimentos[7]);
        } else if (decada_selecionada >= 1990 && decada_selecionada <=1999 || decada_selecionada == 90){
            resultado.setText(acontecimentos[8]);
        } else if (decada_selecionada >= 2000 && decada_selecionada <=2009 || decada_selecionada == 2000){
            resultado.setText(acontecimentos[9]);
        } else if (decada_selecionada >= 2010 && decada_selecionada <=2019 || decada_selecionada == 2010){
            resultado.setText(acontecimentos[10]);
        } else {
            resultado.setText("ERRO! DÉCADA/ANO NÃO RECONHECIDA OU FORA DE NOSSO ACERVO. TENTE NOVAMENTE. . .");
            seletor_decada.setText("");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane resultado;
    private javax.swing.JTextField seletor_decada;
    // End of variables declaration//GEN-END:variables
}
